<?php

/**
 * @file
 * Describe the file
 *
 * @author  Chris Kahn <ckahn@coldfrontlabs.ca>
 */

/**
 * Implements hook_library().
 */
function responsive_tables_library() {
  $libraries['responsive-tables'] = array(
    'title' => 'Responsive Tables',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('responsive-tables') . '/jquery.responsive-tables.js' => array(),
    ),
    'css' => array(
      libraries_get_path('responsive-tables') . '/jquery.responsive-tables.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_preprocess_views_view().
 */
function responsive_tables_preprocess_views_view(&$vars) {
  if (isset($vars['view']->style_plugin->options['responsify']) &&
      $vars['view']->style_plugin->options['responsify'] == TRUE
  ) {
    drupal_add_library('responsive_tables', 'responsive-tables');
  }
}
