<?php

/**
 * @file
 * Describe the file
 *
 * @author  Chris Kahn <ckahn@coldfrontlabs.ca>
 */

/**
 * Implements hook_library().
 */
function responsive_tables_library() {
  $path = drupal_get_path('module', 'responsive_tables');

  $library_path = libraries_get_path('responsive-tables');
  $library_fullpath = $_SERVER['DOCUMENT_ROOT'] . base_path() . $library_path;
  if (!file_prepare_directory($library_fullpath)) {
    $library_path = $path . '/libraries/responsive-tables';
  }

  $libraries['responsive-tables'] = array(
    'title' => 'Responsive Tables',
    'version' => '1.0',
    'js' => array(
      $library_path . '/jquery.responsive-tables.js' => array(),
    ),
    'css' => array(
      $library_path . '/jquery.responsive-tables.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_preprocess_views_view().
 */
function responsive_tables_preprocess_views_view(&$vars) {
  if (isset($vars['view']->style_plugin->options['responsify']) &&
      $vars['view']->style_plugin->options['responsify'] == TRUE
  ) {
    drupal_add_library('responsive_tables', 'responsive-tables');
    drupal_add_js('jQuery(document).ready(function() { jQuery(".view-dom-id-' . $vars['view']->dom_id . ' table").table(); });', array(
      'type' => 'inline',
    ));
  }
}
