<?php

/**
 * @file
 * Describe the file
 *
 * @author  Chris Kahn <ckahn@coldfrontlabs.ca>
 */

/**
 * Implements hook_library().
 */
function responsive_tables_library() {
  $path = drupal_get_path('module', 'responsive_tables') . '/libraries/responsive-tables';

  $libraries['responsive_tables'] = array(
    'title' => 'Responsive Tables',
    'version' => '1.0',
    'js' => array(
      $path . '/jquery.responsive-tables.js' => array(),
    ),
    'css' => array(
      $path . '/jquery.responsive-tables.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
    'dependencies' => array(
      array('system', 'ui.widget'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_preprocess_views_view().
 */
function responsive_tables_preprocess_views_view(&$vars) {
  if (isset($vars['view']->style_plugin->options['responsify']) &&
      $vars['view']->style_plugin->options['responsify'] == TRUE
  ) {
    drupal_add_library('responsive_tables', 'responsive_tables');
    drupal_add_js('jQuery(document).ready(function() { jQuery(".view-dom-id-' . $vars['view']->dom_id . ' table").table(); });', array(
      'type' => 'inline',
    ));
  }
}
